// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class ChatNumber
    {
        public int MemberId { get; set; }
        public string RandomNumber { get; set; }

        public virtual Members Member { get; set; }
    }
}