// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class Citys
    {
        public Citys()
        {
            Areas = new HashSet<Areas>();
            Members = new HashSet<Members>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual ICollection<Areas> Areas { get; set; }
        public virtual ICollection<Members> Members { get; set; }
    }
}