// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class Comments
    {
        public int Id { get; set; }
        public int? MemberTutorRecordId { get; set; }
        public string CommentContent { get; set; }
        public double? Satisfaction { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }

        public virtual MembersTutorRecords MemberTutorRecord { get; set; }
    }
}