// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class Coupons
    {
        public Coupons()
        {
            CouponUsageHistory = new HashSet<CouponUsageHistory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime ExpireTime { get; set; }
        public decimal DiscountMoney { get; set; }
        public int? Condition { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual ICollection<CouponUsageHistory> CouponUsageHistory { get; set; }
    }
}