// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class RevenueTarget
    {
        public RevenueTarget()
        {
            TeachersApply = new HashSet<TeachersApply>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? CreateTime { get; set; }

        public virtual ICollection<TeachersApply> TeachersApply { get; set; }
    }
}