// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Nsl_Api.Models.EFModels
{
    public partial class spGetTeacherTutorPeriodResult
    {
        public string Name { get; set; }
        public DateTime TutorStartTime { get; set; }
        public bool Status { get; set; }
    }
}
