// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class TeacherId
    {
        public TeacherId()
        {
            ChatHistories = new HashSet<ChatHistories>();
            MembersConsumptionRecordDetails = new HashSet<MembersConsumptionRecordDetails>();
            MembersTutorStock = new HashSet<MembersTutorStock>();
            ShoppingCart = new HashSet<ShoppingCart>();
            TeachersDefaultTutorPeriods = new HashSet<TeachersDefaultTutorPeriods>();
            TeachersLanguages = new HashSet<TeachersLanguages>();
            TeachersRealTutorPeriods = new HashSet<TeachersRealTutorPeriods>();
            TeachersSalaryRecords = new HashSet<TeachersSalaryRecords>();
            TeachersTags = new HashSet<TeachersTags>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }

        public virtual Members Member { get; set; }
        public virtual TeachersApply TeachersApply { get; set; }
        public virtual TeachersResume TeachersResume { get; set; }
        public virtual ICollection<ChatHistories> ChatHistories { get; set; }
        public virtual ICollection<MembersConsumptionRecordDetails> MembersConsumptionRecordDetails { get; set; }
        public virtual ICollection<MembersTutorStock> MembersTutorStock { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCart { get; set; }
        public virtual ICollection<TeachersDefaultTutorPeriods> TeachersDefaultTutorPeriods { get; set; }
        public virtual ICollection<TeachersLanguages> TeachersLanguages { get; set; }
        public virtual ICollection<TeachersRealTutorPeriods> TeachersRealTutorPeriods { get; set; }
        public virtual ICollection<TeachersSalaryRecords> TeachersSalaryRecords { get; set; }
        public virtual ICollection<TeachersTags> TeachersTags { get; set; }
    }
}