// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class TeachersResume
    {
        public int TeacherId { get; set; }
        public string Title { get; set; }
        public string Education { get; set; }
        public string WorkExperience { get; set; }
        public string Introduction { get; set; }
        public int? BankCodeId { get; set; }
        public string BankAccount { get; set; }
        public decimal? Price { get; set; }
        public DateTime CreatedTime { get; set; }
        public DateTime ModifiedTime { get; set; }

        public virtual BankCode BankCode { get; set; }
        public virtual TeacherId Teacher { get; set; }
    }
}