// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class TeachersApply
    {
        public int TeacherId { get; set; }
        public int CategoryId { get; set; }
        public int TutorExperienceId { get; set; }
        public int WorkStatusId { get; set; }
        public int TutorHoursOfWeekId { get; set; }
        public int RevenueTargetId { get; set; }
        public string Intro { get; set; }
        public DateTime ApplyTime { get; set; }

        public virtual Categories Category { get; set; }
        public virtual RevenueTarget RevenueTarget { get; set; }
        public virtual TeacherId Teacher { get; set; }
        public virtual TutorExperience TutorExperience { get; set; }
        public virtual TutorHoursOfWeek TutorHoursOfWeek { get; set; }
        public virtual WorkStatus WorkStatus { get; set; }
    }
}