// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class TeacherData
    {
        public string 姓名 { get; set; }
        public string 身份 { get; set; }
        public string 縣市 { get; set; }
        public string 區域 { get; set; }
        public bool? 性別 { get; set; }
        public string 語言 { get; set; }
    }
}