// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Api.Models.EFModels
{
    public partial class Week
    {
        public Week()
        {
            TeachersDefaultTutorPeriods = new HashSet<TeachersDefaultTutorPeriods>();
        }

        public int Id { get; set; }
        public string Day { get; set; }

        public virtual ICollection<TeachersDefaultTutorPeriods> TeachersDefaultTutorPeriods { get; set; }
    }
}