// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class ArticlesClick
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public int? MemberId { get; set; }
        public DateTime ClickTime { get; set; }

        public virtual Articles Article { get; set; }
        public virtual Members Member { get; set; }
    }
}