// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class BankCode
    {
        public BankCode()
        {
            TeachersResume = new HashSet<TeachersResume>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<TeachersResume> TeachersResume { get; set; }
    }
}