// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Nsl_Core.Models.EFModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Nsl_Core.Models.EFModels
{
    public partial interface INSL_DBContextProcedures
    {
        Task<List<spGetMemberTutorPeriodResult>> spGetMemberTutorPeriodAsync(int? MemberId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTeacherTutorPeriodResult>> spGetTeacherTutorPeriodAsync(int? TeacherId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spMessageResult>> spMessageAsync(int? SenderId, int? RecipientId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spMessageDetailResult>> spMessageDetailAsync(int? SenderId, int? RecipientId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
