// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class Languages
    {
        public Languages()
        {
            TeachersLanguages = new HashSet<TeachersLanguages>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual ICollection<TeachersLanguages> TeachersLanguages { get; set; }
    }
}