// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class MembersConsumptionRecords
    {
        public MembersConsumptionRecords()
        {
            MembersConsumptionRecordDetails = new HashSet<MembersConsumptionRecordDetails>();
        }

        public int Id { get; set; }
        public string OrderCode { get; set; }
        public int MemberId { get; set; }
        public int? CouponId { get; set; }
        public int PaymentId { get; set; }
        public bool Status { get; set; }
        public DateTime ConsumeTime { get; set; }

        public virtual Members Member { get; set; }
        public virtual PaymentMethods Payment { get; set; }
        public virtual ICollection<MembersConsumptionRecordDetails> MembersConsumptionRecordDetails { get; set; }
    }
}