// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class MembersTutorRecords
    {
        public MembersTutorRecords()
        {
            Comments = new HashSet<Comments>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public int TeacherTutorPeriodId { get; set; }
        public bool Status { get; set; }
        public DateTime CreateTime { get; set; }

        public virtual Members Member { get; set; }
        public virtual TeachersRealTutorPeriods TeacherTutorPeriod { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}