// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class Roles
    {
        public Roles()
        {
            Members = new HashSet<Members>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Members> Members { get; set; }
    }
}