// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Nsl_Core.Models.EFModels
{
    public partial class spMessageDetailResult
    {
        public int SenderId { get; set; }
        public string SenderName { get; set; }
        public int RecipientId { get; set; }
        public string RecipientName { get; set; }
        public string MessageText { get; set; }
        public DateTime? CreateTime { get; set; }
    }
}
