// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class TeachersLanguages
    {
        public int TeacherId { get; set; }
        public int LanguageId { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual Languages Language { get; set; }
        public virtual TeacherId Teacher { get; set; }
    }
}