// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class TeachersRealTutorPeriods
    {
        public TeachersRealTutorPeriods()
        {
            MembersTutorRecords = new HashSet<MembersTutorRecords>();
        }

        public int Id { get; set; }
        public int TeacherId { get; set; }
        public DateTime TutorStartTime { get; set; }
        public bool Status { get; set; }
        public DateTime CreatedTime { get; set; }

        public virtual TeacherId Teacher { get; set; }
        public virtual ICollection<MembersTutorRecords> MembersTutorRecords { get; set; }
    }
}