// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class TeachersSalaryRecords
    {
        public int Id { get; set; }
        public int TeacherId { get; set; }
        public decimal Price { get; set; }
        public DateTime PayTime { get; set; }

        public virtual TeacherId Teacher { get; set; }
    }
}