// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Nsl_Core.Models.EFModels
{
    public partial class TutorPeriod
    {
        public TutorPeriod()
        {
            TeachersDefaultTutorPeriods = new HashSet<TeachersDefaultTutorPeriods>();
        }

        public int Id { get; set; }
        public string TutorPeriod1 { get; set; }

        public virtual ICollection<TeachersDefaultTutorPeriods> TeachersDefaultTutorPeriods { get; set; }
    }
}